### ISSUE TITLE
prevent `playwright` installation

### ISSUE THREAD

**Issue by unicornware** [chaijs/loupe#72]
## Current behavior

The [`postinstall` script][1] installs `playwright` using `npx`.

When installing `loupe` during a GitHub Actions workflow, this seems to intermittently cause installation errors. I've re-run several workflows, several times, to workaround this.

![Screenshot 2023-11-03 at 2 21 42 AM](https://github.com/chaijs/loupe/assets/20430108/e704f59d-8874-4556-aaa6-6258f89bfbda)

## Expected behavior

Playwright should be not be installed unless defined in my package dependencies.

## Possible solutions

- add `playwright` to `devDependencies`
- refactor `postinstall` script

## Environment

```yaml
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: 4.0.0 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
  npmPackages:
    chai: 5.0.0-alpha.2 => 5.0.0-alpha.2
    loupe: 3.0.0 => 3.0.0 
```

[1]: https://github.com/chaijs/loupe/blob/v3.0.0/package.json#L40
